spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            username: tacocloud
            password: s3cr3tP455w0rd
            database: sleepy_spence

# Setting contact points if the cassandra server isn't running locally:
# spring:
#     cassandra:
#         keyspace-name: tacocloud
#         local-datacenter: datacenter1
#         contact-points:
#         - casshost-1.tacocloud.com
#         - casshost-2.tacocloud.com
#         - casshost-3.tacocloud.com
#         port: 9043

